<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_New</name>
   <tag></tag>
   <elementGuidId>42256ec4-4b4a-47fe-9830-78798180c3c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ppm_workspace_bb&quot;]/div/button[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ppm_workspace_bb&quot;)/div[@class=&quot;ppm_button_bar&quot;]/button[@class=&quot;ppm_button&quot;][count(. | //button[@type = 'button' and (text() = 'New' or . = 'New')]) = count(//button[@type = 'button' and (text() = 'New' or . = 'New')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:urlencoder</name>
      <type>Main</type>
      <value>java:java.net.URLEncoder</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>navigateToURL('nu?action=npt.setObjectUserPartitions','from=Work','navFromActionId=projmgr.projectList','navToActionId=projmgr.projectNew','objectCode=project','ui.page.space=mainnav.work');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppm_button </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ppm_workspace_bb&quot;)/div[@class=&quot;ppm_button_bar&quot;]/button[@class=&quot;ppm_button&quot;]</value>
   </webElementProperties>
</WebElementEntity>
