<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Home PreviousNext Persona</name>
   <tag></tag>
   <elementGuidId>145fff6d-9d0d-4a1c-8903-fac06dc177e5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ppm_nav_app</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ppm_nav_menu ppm_nav_menu_hover</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menu</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Home</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home◀ PreviousNext ▶Personal GeneralOrganizerDashboardsPortletsAdvanced ReportingJobsAccount SettingsOrganizationDepartmentsKnowledge StoreIT Service ManagementServicesPortfolio ManagementProgramsPortfoliosProjectsApplicationsAssetsProductsOther WorkRequirements PlanningRelease PlanningReleasesRequirementsDemand ManagementIdeasIncidentsFinancial ManagementTransaction EntryPost to WIPCreate WIP AdjustmentApprove WIP AdjustmentTransactionsInvoicesCompaniesPosted Transaction ReviewDashboardsPortfolio DashboardStatus Report ReviewCustom ObjectsLookup MappingAdd-In Lookup MappingResource ManagementResourcesResource PlanningCapacity OverviewResource FinderResource RequisitionsTimesheet OverviewSet as HomeReset HomeRefresh</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ppm_nav_app&quot;)</value>
   </webElementProperties>
</WebElementEntity>
