<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>objectttttt</name>
   <tag></tag>
   <elementGuidId>5f689684-eac4-4649-83da-7ab3aa1e52b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//html/body/letznav-app-player/div/letznav-player/flow-list/div[2]/div[1]/div[1]/flow-row/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>flow-row[class=&quot;base-row&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
